apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/deployment.yaml
- ../../base/ingress.yaml
- ../../base/service.yaml

patches:
- path: ./deployment-patch.yaml
  target:
    kind: Deployment
- path: ./ingress-patch.yaml
  target:
    kind: Ingress

images:
- name: samplejava
  newName: ktdseduacr.azurecr.io/edu/samplejava
  newTag: v1.1


