apiVersion : apps/v1
kind: Deployment
metadata:
  name: samplejava
spec:
  replicas: 3
  selector:
    matchLabels:
      app: samplejava
  template:
    metadata:
      labels:
        app: samplejava
    spec:
      containers:
        - name: samplejava
          image: ktdseduacr.azurecr.io/edu/samplejava:v1.3
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Gi"
              cpu: "250m"
          readinessProbe:
            failureThreshold: 3
            successThreshold: 1
            httpGet:
                path: /health
                port: 8080
                scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 3
          livenessProbe:
            failureThreshold: 3
            successThreshold: 1
            httpGet:
                path: /health
                port: 8080
                scheme: HTTP
            initialDelaySeconds: 20