apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: ./ingress-patch.yaml
  target:
    kind: Ingress

images:
- name: ktdseduacr.azurecr.io/edu/samplejava
  newName: ktdseduacr.azurecr.io/edu/samplejava
  newTag: v1.2
