apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/deployment.yaml
- ../../base/service.yaml
- ../../base/ingress.yaml

patchesStrategicMerge:
- deployment.yaml
- ingress.yaml

images:
- name: samplejava
  newName: ktdseduacr.azurecr.io/edu/samplejava
  newTag: v1.1
